import React, { useState } from 'react';
import { UserProfile, Transaction } from '../types';
import { runFullAudit } from '../services/geminiService';
import { Loader2, Download, Mail, CheckCircle, ShieldCheck, Play, Info, FileSignature } from 'lucide-react';
import jsPDF from 'jspdf';
import { UI_TRANSLATIONS } from '../constants';

interface AuditViewProps {
  user: UserProfile;
  transactions: Transaction[];
}

const AuditView: React.FC<AuditViewProps> = ({ user, transactions }) => {
  const [report, setReport] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [emailSending, setEmailSending] = useState(false);
  const [emailSent, setEmailSent] = useState(false);
  const [fiscalYear, setFiscalYear] = useState('2024');

  const t = UI_TRANSLATIONS[user.language]?.audit || UI_TRANSLATIONS['en'].audit;

  const handleGenerateAudit = async () => {
      setLoading(true);
      const res = await runFullAudit(user, transactions);
      setReport(res);
      setLoading(false);
  };

  const handleDownloadPDF = () => {
        if (!report) return;

        const doc = new jsPDF();
        doc.setFontSize(22);
        doc.setTextColor(40, 40, 40);
        doc.text(`AI Compliance Audit (${fiscalYear})`, 20, 20);
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text(`Entity: ${user.companyName || user.name}`, 20, 30);
        doc.text(`Jurisdiction: ${user.country}`, 20, 36);
        doc.text(`Fiscal Year: ${fiscalYear}`, 20, 42);
        doc.line(20, 46, 190, 46);
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        const splitText = doc.splitTextToSize(report || '', 170);
        let y = 55;
        splitText.forEach((line: string) => {
            if (y > 270) { doc.addPage(); y = 20; }
            const cleanLine = line.replace(/\*\*/g, '').replace(/#/g, '').replace(/- /g, '• ');
            doc.text(cleanLine, 20, y);
            y += 6;
        });
        const pageCount = doc.getNumberOfPages();
        for(let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setDrawColor(200, 200, 200);
            doc.line(20, 280, 190, 280);
            doc.setFontSize(7);
            doc.setTextColor(100, 100, 100);
            doc.text("DISCLAIMER: This document is generated by NovaTax AI v2.5 for preparatory purposes.", 20, 285);
            doc.text("For official legal filing, this document must be reviewed and signed by a certified professional.", 20, 289);
            doc.text("NovaTax AI is a software tool and does not provide certified financial advice. External review fees apply.", 20, 293);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(`Page ${i} of ${pageCount}`, 180, 290);
        }
        doc.save(`Audit_Report_${user.companyName || 'User'}_${fiscalYear}.pdf`);
  };

  const handleSendEmail = () => {
      setEmailSending(true);
      setTimeout(() => {
          setEmailSending(false);
          setEmailSent(true);
          setTimeout(() => setEmailSent(false), 3000);
      }, 2000);
  };

  return (
    <div className="max-w-6xl mx-auto h-full flex flex-col pb-12 animate-fade-in">
       {/* Header with Logo */}
       <div className="flex flex-col items-center justify-center mb-10 border-b border-white/5 pb-10 flex-shrink-0">
             <img 
                src="https://fit-4rce-x.s3.eu-north-1.amazonaws.com/NovaTax__logo-invisible-background.png" 
                alt="NovaTax AI" 
                className="w-96 md:w-[600px] object-contain mb-6 filter drop-shadow-[0_0_40px_rgba(168,85,247,0.3)]"
             />
            <h2 className="text-4xl font-bold text-mercury text-center tracking-tight">{t.title}</h2>
            <p className="text-slate-400 text-center mt-2 text-lg"><span className="font-bold text-purple-400 text-glow">{user.country}</span> Regulatory Scan</p>
      </div>

      {/* Visual Disclaimer */}
      <div className="bg-cyan-500/10 border border-cyan-500/20 p-6 rounded-3xl mb-8 flex items-start gap-4 flex-shrink-0 shadow-[0_0_20px_rgba(6,182,212,0.1)]">
          <div className="p-2 bg-cyan-500/20 rounded-full text-cyan-400"><Info size={24} /></div>
          <div>
              <p className="text-cyan-400 text-xs font-bold uppercase tracking-widest mb-2">Important Compliance Notice</p>
              <p className="text-slate-300 text-sm leading-relaxed">
                  This AI Audit generates a preliminary compliance report for your fiscal records. 
                  For international legal filings, this document must be reviewed and signed by a chartered accountant. 
                  <span className="text-white font-bold"> External certification fees are the responsibility of the client.</span>
              </p>
          </div>
      </div>

      <div className="flex flex-col md:flex-row justify-between items-center gap-6 mb-8 flex-shrink-0">
            {/* Year Selector */}
            <div className="flex items-center gap-4 glass-royal px-4 py-2 rounded-full">
                 <span className="text-slate-400 text-xs font-bold uppercase tracking-widest pl-2">{t.selectYear}</span>
                 <select 
                    value={fiscalYear} 
                    onChange={(e) => setFiscalYear(e.target.value)}
                    className="bg-slate-900 text-white text-sm font-bold p-2 rounded-lg border border-white/10 outline-none focus:border-purple-500 cursor-pointer"
                 >
                     <option value="2025">2025</option>
                     <option value="2024">2024</option>
                     <option value="2023">2023</option>
                     <option value="2022">2022</option>
                 </select>
            </div>

            <div className="flex gap-4">
                 {!report ? (
                     <button 
                        onClick={handleGenerateAudit}
                        disabled={loading}
                        className="px-10 py-4 btn-royal text-white font-bold rounded-2xl flex items-center gap-3 transition-all shadow-lg transform hover:-translate-y-1 uppercase tracking-widest text-xs"
                     >
                         {loading ? <Loader2 size={18} className="animate-spin" /> : <Play size={18} />}
                         {loading ? t.generating : t.generate}
                     </button>
                 ) : (
                    <>
                        <button 
                            onClick={handleSendEmail} 
                            disabled={emailSending || emailSent}
                            className={`px-8 py-4 border border-white/10 text-white font-bold rounded-2xl flex items-center gap-2 transition-all shadow-lg uppercase tracking-widest text-xs ${emailSent ? 'bg-emerald-600 border-emerald-500' : 'bg-white/5 hover:bg-white/10'}`}
                        >
                            {emailSending ? <Loader2 size={18} className="animate-spin" /> : emailSent ? <CheckCircle size={18} /> : <Mail size={18} />}
                            {emailSent ? 'Sent' : t.email}
                        </button>
                        <button 
                            onClick={handleDownloadPDF} 
                            className="px-8 py-4 bg-cyan-500 hover:bg-cyan-400 text-black font-bold rounded-2xl flex items-center gap-2 transition-all shadow-[0_0_20px_rgba(6,182,212,0.4)] uppercase tracking-widest text-xs transform hover:-translate-y-1"
                        >
                            <Download size={18} /> {t.download}
                        </button>
                    </>
                 )}
            </div>
      </div>

      {/* Certified Review Upsell - The "Legal" Bridge */}
      {report && (
        <div className="mb-8 bg-purple-900/20 border border-purple-500/30 p-8 rounded-[2.5rem] flex flex-col md:flex-row items-center justify-between gap-8 flex-shrink-0 animate-fade-in shadow-inner relative overflow-hidden">
             <div className="absolute inset-0 bg-gradient-to-r from-purple-600/10 to-transparent"></div>
             <div className="flex items-start gap-6 relative z-10">
                 <div className="p-4 bg-purple-500/20 rounded-full text-purple-400 border border-purple-500/30">
                     <FileSignature size={32} />
                 </div>
                 <div>
                     <h3 className="text-white font-bold uppercase tracking-widest text-sm mb-2 text-mercury">{t.certTitle}</h3>
                     <p className="text-slate-300 text-sm leading-relaxed max-w-xl">
                         {t.certDesc} <strong>{user.country} Partner Network</strong>.
                     </p>
                 </div>
             </div>
             <button className="px-8 py-4 bg-purple-600 hover:bg-purple-500 text-white font-bold text-xs uppercase tracking-widest rounded-2xl transition-all shadow-[0_0_30px_rgba(168,85,247,0.4)] whitespace-nowrap relative z-10 transform hover:scale-105">
                 {t.certBtn}
             </button>
        </div>
      )}

      {/* Report Container */}
      <div className="flex-1 min-h-0 glass-royal rounded-[2.5rem] shadow-2xl relative flex flex-col overflow-hidden border border-white/5">
          {loading && (
             <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/60 backdrop-blur-md z-20">
                <div className="relative mb-6">
                    <div className="absolute inset-0 bg-cyan-500 rounded-full blur-xl opacity-40 animate-pulse"></div>
                    <Loader2 className="animate-spin text-cyan-400 relative z-10" size={64} />
                </div>
                <p className="text-white font-bold animate-pulse tracking-[0.2em] uppercase text-sm">{t.generating}</p>
             </div>
          )}
          
          <div className="flex-1 overflow-y-auto p-12 custom-scrollbar">
            {!report ? (
                <div className="h-full flex flex-col items-center justify-center text-slate-600 opacity-60">
                    <ShieldCheck size={80} className="mb-6" />
                    <p className="text-sm font-bold uppercase tracking-widest">Select Fiscal Year to Begin Audit</p>
                </div>
            ) : (
                <div className="prose prose-invert prose-lg max-w-none pb-20 font-sans">
                     {report.split('\n').map((line, i) => {
                         if (line.startsWith('# ')) return <h1 key={i} className="text-4xl font-bold text-mercury mb-8 mt-10 pb-4 border-b border-white/10">{line.replace('# ', '')}</h1>;
                         if (line.startsWith('## ')) return <h2 key={i} className="text-2xl font-bold text-purple-400 mb-6 mt-10 uppercase tracking-widest">{line.replace('## ', '')}</h2>;
                         if (line.startsWith('- ')) return <div key={i} className="flex gap-3 mb-3 text-slate-300"><span className="text-purple-500 mt-1.5">•</span> <span className="leading-relaxed">{line.replace('- ', '')}</span></div>;
                         if (line.includes('**')) {
                             const parts = line.split('**');
                             return <p key={i} className="mb-4 text-slate-400 leading-relaxed text-lg">{parts.map((part, index) => index % 2 === 1 ? <strong key={index} className="text-white font-bold">{part}</strong> : part)}</p>;
                         }
                         return <p key={i} className="mb-4 text-slate-400 leading-relaxed text-lg">{line}</p>;
                     })}
                </div>
            )}
          </div>
      </div>
    </div>
  );
};

export default AuditView;